name: Feature Request
description: Ask for a feature!
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature
  - type: textarea
    id: feature_ide
    attributes:
      label: What feature would you like to see?
      description: Also tell us, what problem are you trying to solve with this feature?
      placeholder: Tell us what you want!
      value: "This is the feature I want."
    validations:
      required: true
  - type: dropdown
    id: lmrtfy_version
    attributes:
      label: lmrtfy version
      description: What version of lmrtfy are you running?
      options:
        - 0.0.9 (Default)
        - 0.0.8
        - <0.0.8
    validations:
      required: false
  - type: dropdown
    id: python_version
    attributes:
      label: python version
      description: What python version do you use?
      options:
        - ">=3.11"
        - "3.10"
        - "3.9"
        - "3.8"
        - "3.7"
        - "<3.7"
    validations:
      required: false
